networks:
  network_main:

services:
  main:
    image: caddy:2-alpine
    depends_on:
      - one
      - two
      - three
    networks:
      - network_main
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
  
  prometheus:
    image: prom/prometheus
    user: root
    networks:
      - network_main
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - /prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml
  
    
  one:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - network_main
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

  two:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - network_main
    ports:
      - "4000:3000"
    volumes:
      - ./:/app
  
  three:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - network_main
    ports:
      - "8080:3000"
    volumes:
      - ./:/app