networks:
  network_main:

services:
  main:
    image: caddy:2-alpine
    depends_on:
      - one
      - two
      - three
    networks:
      - network_main
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
  
  prometheus:
    image: prom/prometheus
    user: root
    networks:
      - network_main
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - /prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml
  
  opensearch:
    image: opensearchproject/opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Swamisamartha@2003
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    networks:
      - network_main
    ports:
      - "9200:9200"
      - "9600:9600"
    
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - network_main
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
  
    
  one:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - network_main
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

  two:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - network_main
    ports:
      - "4000:3000"
    volumes:
      - ./:/app
  
  three:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - network_main
    ports:
      - "8080:3000"
    volumes:
      - ./:/app